name: Octo Organization CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello from Octo Organization
      - name: script test
        run: ./scripts/test.sh
      - uses: actions/checkout@master
        with:
          repository: xwskx/github-action-test
          path: checkout-test
      - name: list files
        run: ls -la checkout-test
      - name: checkout script test
        run: ./checkout-test/scripts/test.sh
      - name: repo name
        run: echo "${{ github.event.repository.name }}"
